# Generated by Django 5.0.1 on 2024-01-20 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nosaukums')),
                ('program_id', models.PositiveIntegerField(verbose_name='Programmas ID')),
                ('course_id', models.PositiveSmallIntegerField(verbose_name='Kursa ID')),
                ('group_id', models.PositiveIntegerField(verbose_name='Grupas ID')),
                ('semester_program_id', models.PositiveIntegerField(unique=True, verbose_name='Semestra-Programmas ID')),
                ('requests_amount', models.PositiveBigIntegerField(default=1, verbose_name='Pieprasījumu skaits')),
            ],
            options={
                'verbose_name': 'Kalendārs',
                'verbose_name_plural': 'Kalendāri',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nosaukums')),
                ('rtu_id', models.PositiveIntegerField(verbose_name='Semestra RTU ID')),
                ('start_date', models.DateField(verbose_name='Sākuma datums')),
                ('end_date', models.DateField(verbose_name='Beigu datums')),
            ],
            options={
                'verbose_name': 'Semestris',
                'verbose_name_plural': 'Semestri',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.PositiveBigIntegerField(verbose_name='Datuma ID')),
                ('rtu_id', models.PositiveBigIntegerField(verbose_name='Nodarbības ID')),
                ('caldav_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='CalDav ID')),
                ('hash', models.BinaryField(max_length=32, verbose_name='SHA256 event hash')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calendar', verbose_name='Kalendārs')),
            ],
            options={
                'verbose_name': 'Nodarbība',
                'verbose_name_plural': 'Nodarbības',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semester', verbose_name='Semestris'),
        ),
    ]
